[7.5.1][CDE] ApiRGBColor.ToJSON check
ONLYOFFICE/doc-builder-testing pull request #997
Opened 2023-11-30 07:45 UTC by Yar04ek

1.ApiRGBColor.prototype.ToJSON; on review

2023-12-01 08:30 UTC, askonev requested changes

2023-12-01 12:02 UTC, askonev requested changes

2023-12-01 12:02 UTC, askonev commented on spec/docx/smoke/api_rgb_color_spec.rb
> +    lst = rgba['graphic']['spPr']['fill']['fill']['gsLst'][1]['color']['color']['rgba']
Maybe it's an rgba object and not a lst?

2023-12-02 12:43 UTC, l8556 approved these changes

2023-12-02 16:46 UTC, merged